version: "3"

services:
  webserver:
    build: 
      context: ./bin/php8
    container_name: 'chamilo2-php8'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - database
    volumes: 
      - /var/www/chamilo2:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MYSQL_ROOT_PASSWORD: afqc
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    build:
      context: "./bin/mariadb106"
    container_name: 'chamilo2-mariadb106'
    restart: 'always'
    ports:
      - "127.0.0.1:3306:3306"
    volumes: 
      - ./config/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: afqc
      MYSQL_DATABASE: chamilo
      MYSQL_USER: chamilo
      MYSQL_PASSWORD: chamilo
