memory_limit = -1
max_execution_time = 0
post_max_size = 300M
max_input_vars = 3000
upload_max_filesize = 300M

# Xdebug 3

xdebug.mode = debug
#xdebug.start_with_request = yes
#xdebug.discover_client_host = 1
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
#xdebug.idekey = PHPSTORM

session.cookie_httponly = 1

short_open_tag = 0

log_errors_max_len = 0

